version: '3.8'

services:
  sellerboost-db:
    image: postgres:15
    restart: always
    container_name: sellerboost-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sellerboost
      POSTGRES_USER: sellerboost_user
      POSTGRES_PASSWORD: local-dev-password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sellerboost_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres: