// Mock conversations data - for development/testing only
export const mockConversations = [
  {
    id: "1",
    name: "Juan Dela Cruz",
    pageName: "TitaFinds",
    message: "Hi, do you have summer dresses available?",
    time: "2 min ago",
    unread: true,
    profilePic: null,
  },
  {
    id: "2",
    name: "Maria Santos",
    pageName: "TitaFinds",
    message: "How much is the shipping fee to Cebu?",
    time: "15 min ago",
    unread: true,
    profilePic: null,
  },
  {
    id: "3",
    name: "Carlos Reyes",
    pageName: "PC Express",
    message: "Is the RTX 4060 still available?",
    time: "1 hour ago",
    unread: false,
    profilePic: null,
  },
  {
    id: "4",
    name: "Ana Garcia",
    pageName: "ShoeHub",
    message: "Do you have size 8 for the Nike Air Max?",
    time: "2 hours ago",
    unread: false,
    profilePic: null,
  },
  {
    id: "5",
    name: "Robert Chen",
    pageName: "PC Express",
    message: "Thank you for the fast delivery!",
    time: "Yesterday",
    unread: false,
    profilePic: null,
  },
]
